name: Firebase App Distribution

on:
  push:
    branches:
      - main
    tags:  # Moved under the same "push" event
      - 'v*'  # Added quotes for safety
jobs:
  build-and-distribute:  # Remove "null" and indent job properties
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create secrets.properties
        run: |
          echo "google_client_id=${{ secrets.GOOGLE_CLIENT_ID }}" > secrets.properties
          echo "github_client_id=${{ secrets.GH_CLIENT_ID }}" > secrets.properties
          echo "github_client_secret=${{ secrets.GH_CLIENT_SECRET }}" > secrets.properties
          echo "spotify_client_id=${{ secrets.SPOTIFY_CLIENT_ID }}" > secrets.properties
          echo "spotify_client_secret=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> secrets.properties

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      - name: Distribute to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}  # Removed quotes around secret
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: app/build/outputs/apk/release/app-release.apk